### ISSUE TITLE
Add a more complete example for Python installation in OSX (Multi-OS docs)

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1081]
Currently, https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages) has an example on how to handle different Python versions in OS X.

We got a request to include a more detailed custom install script, as we're lacking a complete example.

Here's an example that uses conda to manage the dependencies: https://github.com/zopyx/zopyx.smashdocs/blob/master/install_python.sh

**Comment by ssbarnea** [comment]
@iriberri In fact my impression is that the example does work even if you copy/paste it. I spend lots of hours trying to make Travis build Python on OS X and I was not able to find a working solution yet. 

Can you point me to use repository that succeeds doing this?

**Comment by robertpeteuil** [comment]
My repo successfully builds Python 2.7 & 3.5 in Travis [here](https://github.com/robertpeteuil/aws-shortcuts)

They relevant parts of my .travis.yml file are:
```yaml 
matrix:
  include:
- os: osx
    language: generic
    env: BREW_PYTHON='python'
  - os: osx
    language: generic
    env: BREW_PYTHON='python3'
before_install:
- if [[ $BREW_PYTHON == 'python3' ]]; then brew update; brew install $BREW_PYTHON;
  python3 -m venv venv; source venv/bin/activate; fi
```
