### ISSUE TITLE
Instructions for upgrading Docker fail with 'Unable to locate package docker-ce'

### ISSUE THREAD

**Issue by edmorley** [travis-ci/docs-travis-ci-com#1258]
The Travis Docker docs explain how to update the pre-installed Docker version to a newer version, here:
https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version

Using those steps like so:
```yaml
dist: trusty
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
```

...results in:
```
$ sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce
```

(See: https://travis-ci.org/mozilla/treeherder/builds/242782924#L408)
