### ISSUE TITLE
Document preserving artifacts between stages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#1329]
From https://github.com/travis-ci/beta-features/issues/11#issuecomment-310352970

We'd want to check how this compares to existing documentation, and potentially add this as a separate solution.

---

The following trick can be used to preserve artifacts between stages: enable caching, and store the built artifacts inside the cached directory.

Don't forget to clear the cache directory at the end of the last stage, so that it does not waste space on Travis's infrastructure. You might want to also clear the cache directory at the beginning of the first stage, in case some stale data was not discarded, e.g. after a partially failed build.

It is possible to check in the second and subsequent stages that the cache was populated by the same build by storing `"$TRAVIS_BUILD_ID"` in the cache and then comparing the value.

```
language: c
sudo: false

cache:
  directories:
    - ~/mycache

jobs:
  include:
    - stage: phase1
      install:
      - mv ~/mycache ~/mycache-discard
      - mkdir ~/mycache
      - echo "$TRAVIS_BUILD_ID"
      - echo "$TRAVIS_BUILD_ID" > ~/mycache/travis_build_id
      - echo "build stuff" > ~/mycache/artifact.bin
      script:
      - true
    - stage: phase2
      install:
      - if test "$TRAVIS_BUILD_ID" != `cat ~/mycache/travis_build_id`; then travis_terminate 1; fi
      - rm -f ~/mycache/travis_build_id
      - echo "Do something with ~/mycache/artifact.bin, e.g. publish it to gh-pages"
      - mv ~/mycache ~/mycache-discard
      - mkdir ~/mycache # clear the cache
      script:
      - true
```

Note that the Travis documentation seems to hint that the cache is not updated as part of cron builds, and manually restarted builds. The trick should hopefully work for pull requests, though. Also, I'm not sure how this will behave when a stage contains multiple concurrent jobs which could in principle all populate the cache. Apparently, it is possible to explicitly [specify the cache name](https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices) with an environment variable `CACHE_NAME=FOOBAR`.
