### ISSUE TITLE
Haskell build fails because no cabal file found

### ISSUE THREAD

**Issue by v0d1ch** [travis-ci/docs-travis-ci-com#1414]
I am trying to test the project that pulls in some dependencies from github and puts them in .stack-work/downloads folder. I am receiving message 
```
stack build -j2 --fast --no-terminal
Stack looks for packages in the directories configured in the 'packages' variable defined in your stack.yaml
The current entry points to /home/travis/build/haskell-serbia/haskell-serbia/.stack-work/downloaded/VnEFUOHMFH36/ but no .cabal file could be found there.
```
The folder in question DOES contain .cabal file
My `travis.ci` file looks like this
```
language: haskell


install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x ~/.local/bin/stack


script:
  - stack setup --no-terminal
  - stack build -j2 --fast --no-terminal
  - stack test --fast --no-terminal

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true

```
