### ISSUE TITLE
jobs vs. matrix: What's the difference?

### ISSUE THREAD

**Issue by vinniefalco** [travis-ci/docs-travis-ci-com#1500]
I can't find a reference of all travis.yml keywords. What is the difference between `jobs` and `matrix`?

**Comment by jab** [comment]
Wondering the same myself. One difference I just found: Changing "matrix" to "jobs" and running "travis lint" results in
```
Warnings for .travis.yml:
[x] unexpected key jobs, dropping
```

**Comment by plaindocs** [comment]
Hi @vinniefalco @jab  we're working on that reference. 

In the meantime you can find some info here on jobs and stages

https://docs.travis-ci.com/user/build-stages/

and some info on builds matrixes here

https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

 Cheers

**Comment by MariadeAnton** [comment]
Hi everyone!

As @plaindocs mentioned, we're working on getting the reference updated via https://github.com/travis-ci/docs-travis-ci-com/issues/1476

At the moment, both `matrix.include` and `jobs.include` let you configure and spin up different jobs and one can group jobs in different stages using `jobs.include`. 

Thanks so much for the question!

**Comment by codeselfceo** [comment]
Hello everyone!!

How can I use a folder created in a previous stage on the next stage? For example, 1 stage is build, which will generate a dist folder, 2 stage should deploy that folder.

This is my code:

```
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Install
      name: "Installing dependencies..."
      script: npm install
    - stage: Compile
      skip_cleanup: true
      name: "Building app..."
      script: npm run-script build
    - stage: Deploy
      if: branch = master
      skip_cleanup: true
      name: "Shipping..."
      script: npm run-script deploy
```

I hope you guys can help me, I really need this.

NOTE: anything to say about the file configuration, don't hesitate to say it, I'm totally new with this.

**Comment by apaleyes** [comment]
Do these overwrite each other? If i have both `matrix.include` and `jobs.include` defined, is only one of them executed? This was my experience somehow, but would be nice to hear a more detailed explanation of their behavior

**Comment by BanzaiMan** [comment]
> Do these overwrite each other?

In essence, yes. `matrix` and `jobs` define the same data, so whatever comes at the end will win (which I believe is the YAML spec).

**Comment by BanzaiMan** [comment]
I'm reopening this as a focused subset of #1476 that needs attention specifically.

**Comment by jab** [comment]
https://twitter.com/gvanrossum/status/1086290711266287616

**Comment by abitrolly** [comment]
`os` expansion doesn't work for jobs. In the script below `osx` part is not executed.
```
language: go
go_import_path: github.com/harmony-one/harmony
install:
  - go build -v ./...
script:
  - ./scripts/travis_checker.sh

jobs:
  include:
  - stage: New build script
    os:
      - linux
      - osx
    script:
      - ./build.sh
```

**Comment by dismine** [comment]
@abitrolly i believe your mistake is to put two os in one job. Just try to split os between two jobs inside one stage.

```
jobs:
  include:
  - stage: New build script
    os: linux
    script:
      - ./build.sh
  - os: osx
    script:
      - ./build.sh
```
