### ISSUE TITLE
Document how to manually install MySQL 5.7 on Trusty

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#1605]
We receive lots of requests for MySQL 5.7 and it doesn't come pre-installed.

We should document the following "manual" recipe:

```yaml
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
```

And here's the recipe to reset the root password:

```yaml
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
```
