### ISSUE TITLE
caching wget .deb files?

### ISSUE THREAD

**Issue by cutelittleturtle** [travis-ci/docs-travis-ci-com#1660]
Is there a way to cache .deb downloaded using `wget`? It takes up to half the build time and I really like to get rid of it.

And somehow I don't think the current caching `node_modules` is working either. I still see time spent on `npm install` and `npm install hexo-renderer-pandoc`. But I think I can just get rid of these two commands because the uploaded node_modules folder contains all modules anyways.

Thanks.

```
language: node_js  #设置语言

cache: 
    directories:
        - node_modules
        - $HOME/.npm                                                                                                   

node_js: stable  

python: 3.5 

group: deprecated-2017Q4

branches:
    only:
      - source

install:
  - wget ${pandoc}
  - sudo dpkg -i pandoc*.deb
  - npm install  
  - npm install hexo-renderer-pandoc --save
```
