### ISSUE TITLE
can "github-token: secure: ..." be used for GitHub Pages deployment?

### ISSUE THREAD

**Issue by TheDiveO** [travis-ci/docs-travis-ci-com#1735]
https://docs.travis-ci.com/user/deployment/pages/ for GitHub Pages deployment shows how to use a secure environment variable:

```
deploy:
  provider: pages
    github-token: $GITHUB_TOKEN
```

Instead, is it possible to also use an encrypted token, preferably the same used for release deployment? Such as:

```
deploy:
  provider: pages
    github-token:
      secure: ....
```

Is this posible and a correct way to do it?
