### ISSUE TITLE
Failed to "create extension postgis"

### ISSUE THREAD

**Issue by znz** [travis-ci/docs-travis-ci-com#1951]
https://docs.travis-ci.com/user/database-setup/#using-postgis says 

```
Using PostGIS #
All installed versions of PostgreSQL include PostGIS.

You need to activate the extension in your .travis.yml:

before_script:
  - psql -U postgres -c "create extension postgis"
```

but I added `before_script` using the installed version of PostgreSQL, and It failed.
https://travis-ci.org/znz/memo-app-r/jobs/409501893

I think more steps need in document.

**Comment by plaindocs** [comment]
Hi @znz 

Looks like you're right. Using 

```
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
```

should fix your issue. I'll update the docs.
