### ISSUE TITLE
Used generated folder among stages

### ISSUE THREAD

**Issue by codeselfceo** [travis-ci/docs-travis-ci-com#2000]
Hello everyone!!

How can I use a folder created in a previous stage on the next stage? For example, 1 stage is build, which will generate a dist folder, 2 stage should deploy that folder.

This is my code:
```
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Install
      name: "Installing dependencies..."
      script: npm install
    - stage: Compile
      skip_cleanup: true
      name: "Building app..."
      script: npm run-script build
    - stage: Deploy
      if: branch = master
      skip_cleanup: true
      name: "Shipping..."
      script: npm run-script deploy
```
I hope you guys can help me, I really need this.

NOTE: anything to say about the file configuration, don't hesitate to say it, I'm totally new with this. I tried with `skip_cleanup: true` but I don't know if I can do that.
