### ISSUE TITLE
PostgreSQL 10 configuration is incorrect

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#2674]
As reported in https://travis-ci.community/t/bionic-postgresql-10-no-longer-starts-up/6002,

Our current configuration in https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version

```yaml
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
```

leads to problems.

Followup suggests that `postgresql-10` package is superfluous for Bionic.
