### ISSUE TITLE
Travis CI for R packages: no deploy key found, been trying for hours

### ISSUE THREAD

**Issue by OliBarrington** [travis-ci/docs-travis-ci-com#2699]
Hey Travis CI folks! 

I try to set up a R Package with a pkgdown website, which I want to connect to Travis CI. I'm new to Travis and I don't have any clue why it still fails with the error massage

```yaml
Deploying application
Error: No deploy key found, please setup with `travis::use_travis_deploy()`
Execution halted
Script failed with status 1
failed to deploy
```

Executing the call `travis::use_travis_deploy()` within RStudio returns

```yaml 
> travis::use_travis_deploy()
i Querying Github deploy keys from repo.
i Getting environment variables for `j3ypi/inductive` on Travis CI.
> Deploy keys for Travis CI (`.org`) already present. No action required.
```

This is indicating that everything is as it's supposed to be. When Travis CI sets the environment variables it even says

```yaml
Setting environment variables from repository settings
$ export TRAVIS_DEPLOY_KEY=[secure]
$ export GITHUB_PAT=[secure]
```
For the `.travis.yml` file I oriented towards the one of the dplyr package. It looks like this

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: trusty
cache: packages
latex: false

jobs:
  include:
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
      github-token: $GITHUB_PAT

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
  ```
Does anyone have an idea? Weirdly enough, the deploy key on GitHub says it's never been used. The `GITHUB_PAT`, `R_TRAVIS` and `R_TRAVIS_ORG` variables are specified within the `.Renviron.` The R CMD check passed locally without any errors or warnings.

**Comment by Montana** [comment]
Hey @OliBarrington, 

For your setup, specifically in
 ```R
pkgdown::deploy_site_github()
```
 It looks like the SSH keys are in the wrong location by default. To fix this manually tell/call 
```R 
pkgdown::deploy_site_github()
``` 
Then you'd want to point where to fetch the SSH key (or keys) by modifying your `.travis.yml` file, try editing like the following: 

```yaml
  deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
```
That should actually solve your issue, if it doesn't obviously post back and I'll gladly help you solve it. If you have future problems, please try looking at the [Travis Community Forums](https://travis-ci.community/), as it's easier in aggregate for users to help each other (including myself). 

-Montana (Travis CI Staff)
