### ISSUE TITLE
Coveralls is not being submitted on a Django app with Docker and Travis CI

### ISSUE THREAD

**Issue by OliBarrington** [travis-ci/docs-travis-ci-com#2702]
I'm working on a Django project using Docker. I have configured Travis-Ci and I want to submit test coverage to coveralls. However, it is not working as expected. any help will be highly appreciated.

 ```yaml
 File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/api.py", line 180, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

Here is my current YAML file: 

```yaml
language: python
python:
  - "3.7"
services: docker
before_script: pip install docker-compose
script:
  - docker-compose run web sh -c "coverage run manage.py test && flake8 && coverage report"
after_success:
  - coveralls
```

For extra measure here's my Dockerfile: 

```Dockerfile
FROM python:3.7-alpine
LABEL description="OliBarrington"

ENV PYTHONUNBUFFERED 1

RUN mkdir /oli
WORKDIR /oli

COPY requirements.txt /oli/
RUN apk add --update --no-cache postgresql-client jpeg-dev
RUN apk add --update --no-cache --virtual  .tmp-build-deps gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apk del .tmp-build-deps


COPY . /oli/
```

Here's my docker-compose.yml file: 

```Dockerfile
version: '3.7'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_PORT=5432
    volumes:
      - .:/mwibutsa
    ports:
        - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      ```

**Comment by Montana** [comment]
Hello again @OliBarrington! 

In your case, you are running tests and generating a coverage report inside the container's context then trying to submit a report to coveralls from the global context. 

To understand why the coverage is not being submitted, you have to understand how Docker containers operate.

From looking at your `.travis.yml` file cursory, it would seem you have to run coverage again in the `after_success` command so the .`coverage` data file is present in the container when coveralls runs.

Here's a `.travis.yml` instruction I have setup for you that should build: 

```yaml
language: python
python:
  - "3.7"

services: docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "coverage run manage.py test && flake8 && coverage report"
after_success:
  - docker-compose run web sh -c "coverage run manage.py test && TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls"
```
Next, you need to make sure your git repo files are copied into the Docker container for coveralls to accurately report the branch, and not get branches mixed up, alternatively if this happens you can use `git checkout branch`. 

In your Dockerfile, it's probably worth adding the following: 

```Dockerfile
RUN apk add --update --no-cache postgresql-client jpeg-dev git
```
I think I may have brought it up yesterday, but try checking out the [Travis CI Community Forums](https://travis-ci.community/). I'm on there, so I will definitely lookout for your posts as I've seen you on Travis CI's issues area a lot, and I will always be here to help. 

I hope this solves your issue, 

-Montana (Travis CI Staff)
