### ISSUE TITLE
Travis not starting jobs for multiple python versions

### ISSUE THREAD

**Issue by EcIipse** [travis-ci/docs-travis-ci-com#2704]
I have a Travis YAML file that looks like this:

```yaml
jobs:
  include:
    - stage: "Unit tests"
      language: python
      python:
        - "3.6"
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.client
        ```
I would expect this unit test to run two jobs one for Python 3.6 and one for 3.7. However it always only runs for the first version listed. Am I missing something here? I followed the guide from the official Travis CI docs. This is why I'm posting in thee documentation area.

**Comment by Montana** [comment]
Hey @EcIipse, 

I understand why you're posting in the documentation area in GitHub, but I think I just helped you in the community forums - in the future it would be easier if you'd post there. 

In any event, I looked over your .`travis.yml` file and the Python versions are not defined within the jobs but _are_ define at the root level, I would recommend trying this in your '.travis.yml' file: 

```yaml
python:
  - "3.6"
  - "3.7"
jobs:
```
We recently introduced a build config validation. It can be found under your _Build_ => _View config_ => _Build config validation_.

-Montana
