### ISSUE TITLE
Travis CI - 401 - Build Failing - Bad Credentials on Private Repo

### ISSUE THREAD

**Issue by SolarUltima** [travis-ci/docs-travis-ci-com#2759]
Having some trouble with this build, giving me:

```bash
No stash entries found.
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```
Looked up similar threads, and tried to solve it by going into github - personal tokens, selecting all scopes, but delete repo, and generating a private key there.

Then Using travis encrypt --pro KEY="secretvalue" (pro, since im using travis.com) and updating my travis.yml with the output

```yaml
deploy:
  - provider: releases
    api_key:
      secure: KEY_GENERATED_BY_TRAVIS_ECRYPT_PRO
```
Still fails, Anything else I could try to solve this? Or any place/route I can test my credentials against?
