### ISSUE TITLE
Postgres doesn't seem to be installed by default on bionic

### ISSUE THREAD

**Issue by lbergelson** [travis-ci/docs-travis-ci-com#2766]
Just adding the basic line in the [postgres doc](https://docs.travis-ci.com/user/database-setup/#postgresql) doesn't work with bionic.  

This services line is insufficient
```
services:
  - postgresql
```
You also have to include an addon to specify a version or it doesn't work at all.
```
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
```

The docs should say this.  I didn't do a sweep of all the dists to see which ones work and which don't.
