### ISSUE TITLE
`npm test` script running before stage

### ISSUE THREAD

**Issue by tiagoporto** [travis-ci/docs-travis-ci-com#2768]
I have a sequence of stages with scripts

Example:
```yml
language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: 'Tests and Reports'
    - script: npm run test:coverage && npm run coveralls
      name: Run Unit Tests, generate coverage and publish to coveralls

    - script: npm run test:mutation-report
      name: Run Mutation Tests and publish reports

```

Before each stage is automatically added a `npm test` script

![Screen Shot 2020-05-02 at 6 49 33 PM](https://user-images.githubusercontent.com/3688905/80893162-46e39080-8ca6-11ea-83db-764a91e22040.png)

How to remove this script?

**Comment by BanzaiMan** [comment]
This repository is for Documentation issues. Please use https://travis-ci.community/ for community support.

**Comment by tiagoporto** [comment]
Actually documentation could be improved, I didnt find this information on docs.

> Since npm test is a default test script for `node_js`, Travis CI running this by default, to stop this test case to run add `script: true` line into your first stage, this will skip the default `node_js` step.

```diff
language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: 'Tests and Reports'
+     script: true
    - script: npm run test:coverage && npm run coveralls
      name: Run Unit Tests, generate coverage and publish to coveralls

    - script: npm run test:mutation-report
      name: Run Mutation Tests and publish reports
```

**Comment by BanzaiMan** [comment]
We welcome your PRs.

By the way, that configuration still runs a job with `script: true`, which I don't think is what you want. What you want is:

```yaml
jobs:
  include:
    - stage: 'Tests and Reports'
      script: npm run test:coverage && npm run coveralls
      name: Run Unit Tests, generate coverage and publish to coveralls

    - script: npm run test:mutation-report
      name: Run Mutation Tests and publish reports
```

(This is a variation of the example given in https://docs.travis-ci.com/user/build-stages/#how-to-define-build-stages)
