### ISSUE TITLE
stages + build matrix → what is the best style?

### ISSUE THREAD

**Issue by ataiya** [travis-ci/docs-travis-ci-com#2772]
I have read your [matrix](https://docs.travis-ci.com/user/build-matrix/) and [stages](https://docs.travis-ci.com/user/build-stages/) docs, but there is still something that is not too clear to me.

In regards to the yml script below, I was hoping to use "stages" to have semantic grouping of the entries under "script", but in all examples I saw stages were under the "jobs" matrix expansion.

**Is this really the best yml file one could write to achieve this task?**

```
language: python

before_install:
  - ...
  - pip install -r requirements.txt

jobs:
  include:
    - os: linux
      python: 3.6
      install:
        - pip install -U tensorflow
    - os: linux
      python: 3.6
      install:
        - pip install -U tf-nightly

script:
  # --- run linter
  - flake8 --config=.flake8 ./tensorflow_graphics/
  # --- test the codebase
  - bazel test //tensorflow_graphics/...
  # --- build pip package
  - python setup.py --compute_platform cpu sdist bdist_wheel --universal
  - pip install dist/tensorflow_graphics*.whl
  # --- test the pip package 
  - cd $(mktemp -d) && python -c 'import tensorflow_graphics as tfg'
```
