### ISSUE TITLE
[Question] Deploying to multiple providers in parallel? 

### ISSUE THREAD

**Issue by gondar00** [travis-ci/docs-travis-ci-com#2776]
According to the docs we can deploy to multiple providers using the below
https://docs.travis-ci.com/user/deployment#deploying-to-multiple-providers
```
deploy:
  - provider: cloudcontrol
    email: "YOUR CLOUDCONTROL EMAIL"
    password: "YOUR CLOUDCONTROL PASSWORD"
    deployment: "APP_NAME/DEP_NAME"
  - provider: heroku
    api_key: "YOUR HEROKU API KEY"
```

But this deploys 1st to cloudcontrol & then 2nd to heroku

They do not happen in parallel, what should i do if i want to deploy to providers in parallel?
