### ISSUE TITLE
Multiple workspaces example broken

### ISSUE THREAD

**Issue by LinqLover** [travis-ci/docs-travis-ci-com#2898]
Referring to: https://docs.travis-ci.com/user/using-workspaces#multiple-workspaces-example:~:text=linux-,workspaces%3A,%20%20%20%20%20%20name%3A%20linux%2Dbinaries,-%2D

```yml
      # ...
      workspaces:
        create:
          name: linux-binaries
    - # ...
```

If I'm trying to using this syntax, I get the error:

> workspaces.create must be a hash with keys 'name' and 'paths', or an array of such hashes

Specifying an explicit `paths` value might help.
