### ISSUE TITLE
Wrong deploy key in travis "npm releasing" doc 

### ISSUE THREAD

**Issue by FlamingTuri** [travis-ci/docs-travis-ci-com#2964]
Travis [doc](https://docs.travis-ci.com/user/deployment/npm/) displays the following base config to deploy packages to npm:

```yml
language: node_js
node_js:
  - "12.13"

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
```

However, the deploy step fails since Travis looks for `api_token` instead of `api_key`
