### ISSUE TITLE
IRC notifications over SSL and unstandard ports are undocumented

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/docs-travis-ci-com#428]
*Originally reported at https://github.com/travis-ci/travis-ci/issues/5093*

[The documentation](http://docs.travis-ci.com/user/notifications/#IRC-notification) only talks about `chat.freenode.net#channel` syntax which doesn't say anything about SSL or alternative ports.

It should also have SSL and alternative port example visible somehow:

```yml
notifications:
  irc:
    - "irc://chat.freenode.net:8000/#plaintext_channel"
    - "ircs://chat.freenode.net:7070/#ssl_tls_channel"
```
