### ISSUE TITLE
Problems installing dependencies (snmp) with ubuntu

### ISSUE THREAD

**Issue by TiagoCardoso1983** [travis-ci/docs-travis-ci-com#592]
My apologies if this is not the best place, but I don't have a twitter account and the other repos don't allow issues. Feel free to redirect me to the proper place.

I'm testing this ruby gem which binds to the native C netsnmp library using FFI. It therefore expects both
```libnetsnmp.so``` and ```netsnmp.so``` to be available and linkable (at least this is what I have locally in my centOS env). This seems, however, not to be the case in my travis build. Here's the relevant parts:

```yaml
before_install:                  
  - sudo apt-get update          
  - sudo apt-get install -y snmp 
  - sudo apt-get install -y snmpd
...
# this is what I tried to correct it
before_script:                                                     
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib
...
script: bundle exec rake
```
This was the error:

```
1.24s$ bundle exec rake
/usr/local/rvm/rubies/ruby-2.0.0-p647/bin/ruby -I/home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/rspec-core-3.3.2/lib:/home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/rspec-support-3.3.0/lib /home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libnetsnmp': libnetsnmp: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libnetsnmp.so': libnetsnmp.so: cannot open shared object file: No such file or directory.
Could not open library 'netsnmp': netsnmp: cannot open shared object file: No such file or directory
	from /home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
	from /home/travis/build/swisscom/ruby-netsnmp/.bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
	from /home/travis/build/swisscom/ruby-netsnmp/lib/netsnmp/core/libsnmp.rb:4:in `<module:LibSNMP>'
	from /home/travis/build/swisscom/ruby-netsnmp/lib/netsnmp/core/libsnmp.rb:2:in `<module:Core>'
...
```

Available [here](https://travis-ci.org/swisscom/ruby-netsnmp/builds/131087421)

I'm not sure why the object files are not exposed to the environment. A possible solution could be to "whitelist" snmp package for travis, as well. But important is to find a way to programatically find the .so files, as I'd like to test it for osx (and eventually windows, if netsnmp is supported there).
