### ISSUE TITLE
Document Java Version on OSX

### ISSUE THREAD

**Issue by JLLeitschuh** [travis-ci/docs-travis-ci-com#593]
The documentation here doesn't include what version of the JDK is provided.
Can this be configured using the build matrix?
I believe, (at the moment) only Oracle JDK 7 is available.

https://docs.travis-ci.com/user/osx-ci-environment/#Compilers-and-Build-toolchain

**Comment by BanzaiMan** [comment]
We do not support switching JDK versions on OS X. https://github.com/travis-ci/travis-ci/issues/2317

**Comment by JLLeitschuh** [comment]
You should have the default version listed though. So that it is clear what version is offered.

**Comment by plaindocs** [comment]
@acnagy this is related to our previous PR. 

We should definitely show the current default version of JDK on default OSX even if we don't provide a full list of other versions.

**Comment by acnagy** [comment]
@plaindocs Agreed! I'll ping you once with a PR for that soon.

**Comment by BanzaiMan** [comment]
It is definitely worth adding this information in the documents for those old images that will not see updates.

Going forward, though, a better option would be to incorporate [system_info](https://github.com/travis-ci/system-info/) into the macOSX image provisioning process so that this information is automatically updated.

**Comment by dwijnand** [comment]
For a snapshot in time, it looks like all osx images are oraclejdk8, in particular:

```yaml
osx_image: xcode8   # oraclejdk8 1.8.0_92-b14
osx_image: xcode7.3 # oraclejdk8 1.8.0_74-b02
osx_image: xcode7.2 # oraclejdk8 1.8.0_66-b17
osx_image: xcode7.1 # oraclejdk8 1.8.0_66-b17
osx_image: xcode7   # oraclejdk8 1.8.0_66-b17
osx_image: xcode6.4 # oraclejdk8 1.8.0_45-b14
```

**Comment by JLLeitschuh** [comment]
Thank you Travis CI. You guys are awesome. Keep up the good work!
You have just made builds everywhere that much easier to setup!

**Comment by MariadeAnton** [comment]
Thank you so much for the extra info, @dwijnand - that's super helpful!

@acnagy Does this help updating the docs mentioning that the one with Oracle JDK 7 is Xcode 6.1?

```yaml
osx_image: beta-xcode6.3 # 1.8.0_45-b14
osx_image: beta-xcode6.2 # 1.8.0_40-b25
osx_image: beta-xcode6.1 # 1.7.0_45-b18
```
