### ISSUE TITLE
Document locale support in build matrix

### ISSUE THREAD

**Issue by stonio** [travis-ci/docs-travis-ci-com#647]
- Can you document how to test against several OS locales?
- Can you document how to set JVM locale?

A basic need is to run Apache Maven integration tests with different locales (part of the "build matrix"). Could you provide such an example?

**Comment by BanzaiMan** [comment]
You can set up a matrix with varying `LOCALE` values. How does one set locales on JVM? Should it not respect `LOCALE` thus set?

**Comment by stonio** [comment]
To run Maven test with differents locales, I have updated `.travis.yml` as follow:
```yml
env:
  - USER_LANGUAGE=en USER_COUNTRY=US
  - USER_LANGUAGE=de USER_COUNTRY=DE

before_install:
  - echo "MAVEN_OPTS='-Duser.language=$USER_LANGUAGE -Duser.country=$USER_COUNTRY'" > ~/.mavenrc
```

I think current Travis-Ci documentation lacks of information for running scripts/tests in different locales.
