### ISSUE TITLE
HTTP Basic auth + SSL for elasticsearch?

### ISSUE THREAD

**Issue by amihaiemil** [travis-ci/docs-travis-ci-com#653]
In the CI environment I have an elasticsearch 1.7 instance, configured in ``.travis.yml`` like this:
```
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
services:
  - elasticsearch

before_install:
  - sleep 10

install: true
```
As mentioned in [here](https://www.elastic.co/de/blog/found-elasticsearch-security) (section **Suggested Solutions**), I would like to setup some sort of proxy to have basic auth required before accessing elasticsearch. 

Can this be achieved and if yes, how? 

Thanks,
Mihai Andronache
