### ISSUE TITLE
Double check slack PR notifications 

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#687]
https://github.com/travis-pro/team-teal/issues/1088

**Comment by MariadeAnton** [comment]
This currently applies to notifications and encrypted environment variables. 

Currently, encrypted environment variables are stored in a nested hash which causes the  extra key, for example `on_pull_requests: false` not to be taken into account when using a formatting like: 

notifications:
  slack:
    on_pull_requests: false
    secure: long-encrypted-value

Alternatively, one would need to use and additional key: 

```yaml
notifications:
  slack:
    on_pull_requests: false
    rooms: 
      - secure: long-encrypted-value
```

In which `long-encrypted-value` is generated using `travis encrypt "TeamName:token"

As an example, here's the commit that made it work properly: https://github.com/MariadeAnton/travis_production_test/compare/da753b8650e8...56799df4acf7

**Comment by iriberri** [comment]
It looks like this is also happening with `on_change` keys:

```yml
notifications:
  slack:
    on_success: change
    secure: xxxx
```

We've received some reports of Slack notifications being sent always, and not only on change. After investigating these builds and their previous status, everything points to this issue here.
