### ISSUE TITLE
 Android SDK Platform-tools revision Android-25

### ISSUE THREAD

**Issue by Lyoness** [travis-ci/docs-travis-ci-com#779]
Update travis.yml configuration for `android.components:` portion to work with Android-25

https://secure.helpscout.net/conversation/249893397/34943/?folderId=30784

**Comment by MariadeAnton** [comment]
besides from that, the way to list the build tools would be:

`build-tools-25.0.0`

**Comment by MariadeAnton** [comment]
To recap:

```yaml

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
```

There's some more information available at https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
